### ISSUE TITLE
ImportError: cannot import name 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by mkarlovich** [oasis-open/cti-stix-validator#153]
I'm trying to run stix2_validator on Ubuntu after installing with pip keep getting this error:

```
$ ./stix2_validator
Traceback (most recent call last):
  File "./stix2_validator", line 5, in <module>
    from stix2validator.scripts.stix2_validator import main
  File "/usr/local/lib/python3.6/dist-packages/stix2validator/__init__.py", line 6, in <module>
    from .errors import NoJSONFileFoundError, ValidationError
  File "/usr/local/lib/python3.6/dist-packages/stix2validator/errors.py", line 5, in <module>
    from six import python_2_unicode_compatible, text_type
ImportError: cannot import name 'python_2_unicode_compatible'
```
Installed using Python 3.6.2, pip 20.2.3

**Comment by clenk** [comment]
Hi @mkarlovich, can you confirm what version of `six` you have installed in your environment?

This code will be removed in a future version since we've dropped python 2 support but upgrading the version of `six` may fix it in the meantime.

**Comment by mkarlovich** [comment]
@clenk It's version 1.11.0
